apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-extra-resources
parameters:
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SPAWNER_APPLICATION}-res
    namespace: ${SPAWNER_NAMESPACE}
    labels:
      app: ${SPAWNER_APPLICATION}-${SPAWNER_NAMESPACE}
      spawner: learning-portal
  data:
    extra_resources.yaml: |-
        kind: List
        apiVersion: v1
        items:
        - kind: ServiceAccount
          apiVersion: v1
          metadata:
            name: pipeline
        - kind: ClusterRole
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: ${project_namespace}-pipelines
          rules:
          - apiGroups:
            - security.openshift.io
            resources:
            - securitycontextconstraints
            verbs:
            - use
            resourceNames:
            - privileged
        - kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: pipelines-privileged-scc
          subjects:
          - kind: ServiceAccount
            name: pipeline
            namespace: "${project_namespace}"
          roleRef:
            kind: ClusterRole
            apiGroup: rbac.authorization.k8s.io
            name: ${project_namespace}-pipelines
